### ISSUE TITLE
Multiples MobileServicePushFailedException

### ISSUE THREAD

**Issue by omar25vx** [Azure/azure-mobile-apps-android-client#102]
The callbacks work fine, but for no reason at some point this error appears and it is no longer possible to remove it until it clears the application cache, Pull and Push

java.util.concurrent.ExecutionException: com.microsoft.windowsazure.mobileservices.table.sync.push.MobileServicePushFailedException
 at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401)
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)

**Comment by elamalani** [comment]
@omar25vx We haven't heard back from you. I'm closing the issue for now but please feel free to reach out to us if you have any questions. Thanks!
