### ISSUE TITLE
Application crashes when it returns to app from OAuth callback in version 3.5.1

### ISSUE THREAD

**Issue by iamdamjanmiloshevski** [Azure/azure-mobile-apps-android-client#150]
Full log:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mk.cboards.geonosis, PID: 830
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/common/util/concurrent/SettableFuture;
        at com.microsoft.windowsazure.mobileservices.authentication.TokenRequestAsyncTask.<init>(TokenRequestAsyncTask.java:60)
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.performCodeExchange(CustomTabsLoginActivity.java:300)
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.exchangeAuthCodeForToken(CustomTabsLoginActivity.java:272)
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.onResume(CustomTabsLoginActivity.java:135)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446)
        at android.app.Activity.performResume(Activity.java:7939)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.common.util.concurrent.SettableFuture" on path: DexPathList[[zip file "/data/app/mk.cboards.geonosis-bgvZiKXGS7oHUWxfvgcg1Q==/base.apk"],nativeLibraryDirectories=[/data/app/mk.cboards.geonosis-bgvZiKXGS7oHUWxfvgcg1Q==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.microsoft.windowsazure.mobileservices.authentication.TokenRequestAsyncTask.<init>(TokenRequestAsyncTask.java:60) 
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.performCodeExchange(CustomTabsLoginActivity.java:300) 
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.exchangeAuthCodeForToken(CustomTabsLoginActivity.java:272) 
        at com.microsoft.windowsazure.mobileservices.authentication.CustomTabsLoginActivity.onResume(CustomTabsLoginActivity.java:135) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1446) 
        at android.app.Activity.performResume(Activity.java:7939) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

dependencies:
    implementation 'com.microsoft.azure:azure-mobile-android:3.5.1@aar'
    implementation 'com.android.support:customtabs:23.0.1'
Manifest:
```xml
<application>
    <activity android:name="com.microsoft.windowsazure.mobileservices.authentication.RedirectUrlActivity">
      <intent-filter>
        <action android:name="android.intent.action.VIEW" />

        <category android:name="android.intent.category.DEFAULT" />
        <category android:name="android.intent.category.BROWSABLE" />

        <data
            android:host="easyauth.callback"
            android:scheme="my-scheme"
            />
      </intent-filter>
    </activity>
  </application>
```

**Comment by MatkovIvan** [comment]
Hi @iamdamjanmiloshevski 

The missing class is from Guava library. It's most likely dependency version conflict or so.
Could you please check what version of it do you use?

Thanks,
Ivan

**Comment by iamdamjanmiloshevski** [comment]
Hello Ivan, 
Unfortunately, I do not use Guava in my project. The image processing library I use is Picasso. 
I figured out that it's a dependency version problem, because I googled the problem before  sharing here, I even tried downgrading OkHttp library and OkHttpILoggingInterceptor libraries but the problem is not fixed, I even tried it on another project without Picasso or Guava, still the same problem exists, therefore it has to be with the code or the dependencies this library uses.

**Comment by MatkovIvan** [comment]
This SDK uses v18:
https://github.com/Azure/azure-mobile-apps-android-client/blob/265b4852f8cb7a9ea2fb260172662b66acd0bb10/sdk/src/sdk/build.gradle#L43

Please try to use the same version to avoid conflicts

**Comment by iamdamjanmiloshevski** [comment]
@MatkovIvan, I mentioned that our project does not use Guava explicitly, but I think some other dependency is using it, therefore it can be found in the external libraries folder. 
However after adding the Guava dependency in the gradle script I get the following error when building the app `ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.google.guava:guava:18.0.`
By the way, if the SDK uses Guava and it has it already imported in it's gradle, why do I need to import it again? 
Could you please be more descriptive and helpful in your answers. 
Thank you. 

Gradle script dependencies from Imported module where I use the SDK
`dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation "com.squareup.moshi:moshi:$moshiVersion"
    implementation "com.squareup.retrofit2:retrofit:$retrofit2Version"
    implementation "com.squareup.retrofit2:converter-moshi:$retrofit2Version"
    implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofit2Version"
    compileOnly "com.google.auto.value:auto-value-annotations:$autoValueVersion"
    annotationProcessor "com.google.auto.value:auto-value:$autoValueVersion"
    compileOnly 'com.google.auto.factory:auto-factory:1.0-beta5'
    annotationProcessor 'com.google.auto.factory:auto-factory:1.0-beta5'
    compileOnly 'com.ryanharter.auto.value:auto-value-moshi-annotations:0.4.3'
    annotationProcessor 'com.ryanharter.auto.value:auto-value-moshi:0.4.3'
    annotationProcessor "com.ryanharter.auto.value:auto-value-parcel:0.2.6"
    compileOnly 'com.ryanharter.auto.value:auto-value-parcel-adapter:0.2.6'
    implementation "com.google.dagger:dagger:$daggerVersion"
    //implementation("com.squareup.okhttp3:okhttp:$okhttp3Version")
    annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    implementation 'com.f2prateek.rx.preferences2:rx-preferences:2.0.0-RC2'
    implementation 'com.google.code.gson:gson:2.8.2'
    implementation 'com.microsoft.azure:azure-mobile-android:3.5.1@aar'
    implementation 'com.squareup.okhttp3:okhttp:3.12.1'
    implementation 'com.android.support:customtabs:26.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}`
Gradle script dependencies from the project where the module is used:
`dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    implementation project(':naboo')
    compile "com.android.support:support-v4:$supportLibVersion"
    compile "com.android.support:support-annotations:$supportLibVersion"
    compile "com.android.support:appcompat-v7:$supportLibVersion"
    compile "com.android.support:recyclerview-v7:$supportLibVersion"
    compile "com.android.support:design:$supportLibVersion"
    compile "com.android.support:percent:$supportLibVersion"
    compile "com.android.support:exifinterface:$supportLibVersion"
    compile "com.android.support:support-vector-drawable:$supportLibVersion"
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    compile "com.bluelinelabs:conductor:$conductorVersion"
    compile "com.bluelinelabs:conductor-support:$conductorVersion"
    compile "com.bluelinelabs:conductor-rxlifecycle2:$conductorVersion"
    compile "com.google.dagger:dagger:$daggerVersion"
    annotationProcessor "com.google.dagger:dagger-compiler:$daggerVersion"
    compile "com.google.dagger:dagger-android:$daggerVersion"
    compile "com.google.dagger:dagger-android-support:$daggerVersion"
    annotationProcessor "com.google.dagger:dagger-android-processor:$daggerVersion"
    provided 'com.google.auto.value:auto-value:1.3'
    annotationProcessor 'com.google.auto.value:auto-value:1.3'
    provided 'com.google.auto.factory:auto-factory:1.0-beta5'
    annotationProcessor 'com.google.auto.factory:auto-factory:1.0-beta5'
    provided 'com.ryanharter.auto.value:auto-value-moshi-annotations:0.4.3'
    annotationProcessor 'com.ryanharter.auto.value:auto-value-moshi:0.4.3'
    compile "com.squareup.okhttp3:okhttp:$okhttp3Version"
    compile "com.squareup.okhttp3:logging-interceptor:$okhttp3Version"
    implementation 'com.squareup.okio:okio:1.12.0'
    implementation 'com.squareup.picasso:picasso:2.71828'
    compile "com.squareup.retrofit2:retrofit:$retrofit2Version"
    compile "com.squareup.retrofit2:converter-moshi:$retrofit2Version"
    compile "com.squareup.retrofit2:adapter-rxjava2:$retrofit2Version"
    implementation 'com.squareup.moshi:moshi:1.4.0'
    implementation 'com.github.bumptech.glide:glide:4.0.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0'
    compile "com.jakewharton:butterknife:$butterKnifeVersion"
    annotationProcessor "com.jakewharton:butterknife-compiler:$butterKnifeVersion"
    implementation 'com.jakewharton.timber:timber:4.5.1'
    implementation 'com.jakewharton.byteunits:byteunits:0.9.1'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.0.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-support-v4:2.0.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-appcompat-v7:2.0.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-design:2.0.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-recyclerview-v7:2.0.0'
//    debugCompile "com.squareup.leakcanary:leakcanary-android:$leakCanaryVersion"
//    releaseCompile "com.squareup.leakcanary:leakcanary-android-no-op:$leakCanaryVersion"
    implementation 'io.reactivex.rxjava2:rxjava:2.1.0'
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'com.jakewharton.threetenabp:threetenabp:1.0.4'
    implementation 'com.f2prateek.rx.preferences2:rx-preferences:2.0.0-RC2'
    implementation 'fr.avianey.com.viewpagerindicator:library:2.4.1.1@aar'
    annotationProcessor 'com.ryanharter.auto.value:auto-value-parcel:0.2.5'
    compile('com.crashlytics.sdk.android:crashlytics:2.6.8@aar') {
        transitive = true
    }
    androidTestCompile 'junit:junit:4.12'
    androidTestCompile "com.android.support.test.espresso:espresso-core:$espressoVersion"
    androidTestCompile("com.android.support.test.espresso:espresso-contrib:$espressoVersion") {
        exclude group: 'com.android.support'
    }
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test:rules:0.5'
    androidTestCompile 'com.google.code.findbugs:jsr305:3.0.1'
    testCompile 'junit:junit:4.12'
    testCompile 'com.google.truth:truth:0.30'
    implementation 'android.arch.lifecycle:viewmodel:1.1.1'
    implementation 'android.arch.lifecycle:livedata:1.1.1'
    implementation 'android.arch.lifecycle:extensions:1.1.1'
    implementation 'com.hmomeni.progresscircula:progresscircula:0.2.1'
    implementation 'com.google.android.exoplayer:exoplayer:2.7.3'

    implementation 'com.facebook.android:facebook-login:[5,6)'
    implementation 'com.vanniktech:emoji-google:0.6.0'
    implementation 'com.vanniktech:emoji-ios:0.6.0'
    implementation 'com.vanniktech:emoji-twitter:0.6.0'

    implementation 'com.karumi:dexter:5.0.0'
    implementation 'com.agrawalsuneet.androidlibs:dotsloader:1.4'
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'com.android.support:cardview-v7:26.0.0'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.7.0'

    implementation "com.microsoft.appcenter:appcenter-analytics:2.3.0"
    implementation "com.microsoft.appcenter:appcenter-crashes:2.3.0"
}`

**Comment by MatkovIvan** [comment]
> our project does not use Guava explicitly, but I think some other dependency is using it

Yes, that's what causes a version conflict.

> By the way, if the SDK uses Guava and it has it already imported in it's gradle, why do I need to import it again?

You don't need to do it in simple cases, gradle do that work for you.

Based on the list of your dependencies, guava v19 is required for `com.google.auto.factory`.
BTW You can use `dependencies` gradle task to get more information what's going on in your project dependencies (you can read more about it here: https://docs.gradle.org/current/userguide/inspecting_dependencies.html)

So, I guess the problem is clear and we can treat this issue as a feature request "update guava", right?

**Comment by iamdamjanmiloshevski** [comment]
Yes ok, I just went through again the previous issues with the SDK and found [this](https://github.com/Azure/azure-mobile-apps-android-client/issues/105), I will try it. 

Thank you @MatkovIvan  for your assistance.

**Comment by iamdamjanmiloshevski** [comment]
@MatkovIvan adding     compile 'com.google.guava:guava:23.2-android' to my gradle files in the module of the app, fixed the problem. Thank you...

**Comment by MatkovIvan** [comment]
Ok, I'm glad the problem is resolved. Feel free to open new issues if you have any other questions
